services:
  app:
    build:
      context: ./node
    container_name: app
    entrypoint: bash -c "npm install && dockerize -wait tcp://db:3306 -timeout 20s node index.js"
    networks:
      - fullcycle
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fullcycle
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullcycle

  nginx:
    image: nginx:1.27.2-alpine
    container_name: nginx
    tty: true
    networks:
      - fullcycle
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

networks:
  fullcycle:
    driver: bridge
